import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  data: [
    {
      id: 1,
      img: "/assets/person.jpg",
      author: "Abul Hasem",
      name: "Role",
      inputs: 1,
      db: "mongodb",
      crud: false,
      ws: true,
      inMemory: true,
      relation: ["Role", "Permission", "+2"],
      status: true,
      action: true,
    },
    {
      id: 2,
      img: "/assets/person.jpg",
      author: "Sunny",
      name: "Permission",
      inputs: 2,
      db: "postgres",
      crud: true,
      ws: true,
      inMemory: true,
      relation: ["Role", "Permission", "+2"],
      status: true,
      action: true,
    },
    {
      id: 3,
      img: "/assets/person.jpg",
      author: "Maruf",
      name: "User",
      inputs: 3,
      db: "sqlite",
      crud: true,
      ws: true,
      inMemory: true,
      relation: ["Role", "Permission", "+2"],
      status: true,
      action: true,
    },
    {
      id: 4,
      img: "/assets/person.jpg",
      author: "Mijan",
      name: "User",
      inputs: 4,
      db: "mysql",
      crud: false,
      ws: true,
      inMemory: true,

      relation: ["Role", "Permission", "+2"],
      status: true,
      action: true,
    },
    {
      id: 5,
      img: "/assets/person.jpg",
      author: "Yeasir",
      name: "User",
      inputs: 5,
      db: "",
      crud: true,
      ws: true,
      inMemory: true,
      relation: ["Permission", "+2"],
      status: true,
      action: true,
    },
    {
      id: 6,
      img: "/assets/person.jpg",
      author: "Imran",
      name: "User",
      inputs: 6,
      db: "mongoose",
      crud: true,
      ws: true,
      inMemory: true,
      relation: ["Role", "+2"],
      status: true,
    },
    {
      id: 7,
      img: "/assets/person.jpg",
      author: "Toukir raju",
      name: "User",
      inputs: 7,
      db: "postgres",
      crud: false,
      ws: true,
      inMemory: true,
      relation: ["Role", "Permission"],
      status: false,
      action: true,
    },
    {
      id: 9,
      img: "/assets/person.jpg",
      name: "User",
      inputs: 8,
      db: "mongodb",
      crud: false,
      ws: true,
      inMemory: true,
      relation: ["Role", "Permission", "+2"],
      status: true,
      action: true,
    },
    {
      id: 10,
      img: "/assets/person.jpg",
      name: "User",
      inputs: 9,
      db: "mongodb",
      crud: false,
      ws: true,
      inMemory: true,
      relation: ["Role", "Permission", "+2"],
      status: true,
      action: true,
    },
    {
      id: 11,
      img: "/assets/person.jpg",
      name: "User",
      inputs: 10,
      db: "mongodb",
      crud: false,
      ws: true,
      inMemory: true,
      relation: ["Role", "Permission", "+2"],
      status: true,
      action: true,
    },
    {
      id: 12,
      img: "/assets/person.jpg",
      name: "Broker",
      inputs: 11,
      db: "mongodb",
      crud: false,
      ws: true,
      inMemory: true,
      relation: ["Role", "Permission", "+2"],
      status: true,
      action: true,
    },
    {
      id: 13,
      img: "/assets/person.jpg",
      name: "WithUser",
      inputs: 12,
      db: "mongodb",
      crud: false,
      ws: true,
      inMemory: true,
      relation: ["Role", "Permission", "+2"],
      status: true,
      action: true,
    },
    {
      id: 14,
      img: "/assets/person.jpg",
      name: "NonUser",
      inputs: 13,
      db: "mongodb",
      crud: false,
      ws: true,
      inMemory: true,
      relation: ["Role", "Permission", "+2"],
      status: true,
      action: true,
    },
  ],
};
const tableSlice = createSlice({
  name: "tableData",
  initialState,
  reducers: {
    updateTableSlice: (state, { payload }) => {
      state.data = payload;
    },
  },
});
export const { updateTableSlice } = tableSlice.actions;
export default tableSlice.reducer;
